{"name": "Wrong data authorization", "status": "passed", "steps": [{"name": "open the login page...", "status": "passed", "steps": [{"name": "open the page", "status": "passed", "start": 1714430850905, "stop": 1714430851254}], "start": 1714430850905, "stop": 1714430851254}, {"name": "log in with the wrong username and password...", "status": "passed", "steps": [{"name": "open the page", "status": "passed", "start": 1714430851254, "stop": 1714430851266}, {"name": "fill in the fields...", "status": "passed", "start": 1714430851266, "stop": 1714430851368}, {"name": "click the login button...", "status": "passed", "start": 1714430851368, "stop": 1714430851408}], "start": 1714430851254, "stop": 1714430851408}, {"name": "check the current url and the error message is provided...", "status": "passed", "steps": [{"name": "get the current page url", "status": "passed", "start": 1714430851408, "stop": 1714430851410}], "start": 1714430851408, "stop": 1714430851410}], "start": 1714430850905, "stop": 1714430851411, "uuid": "75a6c54c-92a5-4775-bc0c-15288e3e504c", "historyId": "a363dc6ddc6eefff65751817dda3e628", "testCaseId": "a363dc6ddc6eefff65751817dda3e628", "fullName": "tests.test_1_login.TestLogin#test_auth_negative_wrong_login", "labels": [{"name": "epic", "value": "Auth page"}, {"name": "as_id", "value": "1.5"}, {"name": "feature", "value": "Auth"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_1_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "POLA-AI"}, {"name": "thread", "value": "1076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_1_login"}]}