{"name": "wrong data authorization", "status": "passed", "steps": [{"name": "open the page", "status": "passed", "start": 1714180596559, "stop": 1714180596870}, {"name": "log in with the wrong username and password", "status": "passed", "start": 1714180596870, "stop": 1714180596984}, {"name": "check the current url and the error message is provided", "status": "passed", "steps": [{"name": "get the current page url", "status": "passed", "start": 1714180596984, "stop": 1714180596987}], "start": 1714180596984, "stop": 1714180596987}], "start": 1714180596559, "stop": 1714180596987, "uuid": "29553983-4a81-4dfc-8cef-62f862b9699d", "historyId": "a363dc6ddc6eefff65751817dda3e628", "testCaseId": "a363dc6ddc6eefff65751817dda3e628", "fullName": "tests.test_1_login.TestLogin#test_auth_negative_wrong_login", "labels": [{"name": "feature", "value": "auth"}, {"name": "as_id", "value": "1.5"}, {"name": "epic", "value": "auth page"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_1_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "POLA-AI"}, {"name": "thread", "value": "24372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_1_login"}]}